# fly.toml app configuration file generated for eva-vid on 2023-11-26T12:50:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eva-vid"
primary_region = "jnb"

[build]
  builder = "paketobuildpacks/builder:base"

[env]

[http_service]
  internal_port = 5001 
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
