# fly.toml app configuration file generated for eva-vid-still-moon-1655 on 2023-11-26T18:37:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eva-vid-still-moon-1655"
primary_region = "jnb"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
